"""update users table

Revision ID: 43b5cf6c0d38
Revises: 9cc64eed16e7
Create Date: 2026-07-24 16:10:13.473645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b5cf6c0d38'
down_revision: Union[str, Sequence[str], None] = '9cc64eed16e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new columns with defaults
    op.add_column(
        "users",
        sa.Column(
            "full_name",
            sa.String(length=255),
            nullable=False,
            server_default="Unknown"
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        ),
    )

    # Remove username constraint
    op.drop_constraint(
        "users_username_key",
        "users",
        type_="unique",
    )

    # Remove old column
    op.drop_column(
        "users",
        "username",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
