"""update alerts table

Revision ID: 9cc64eed16e7
Revises: 7852101d5e9a
Create Date: 2026-07-24 15:19:11.874133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cc64eed16e7'
down_revision: Union[str, Sequence[str], None] = '7852101d5e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('alert_type', sa.String(length=100), nullable=False))
    op.add_column('alerts', sa.Column('message', sa.Text(), nullable=False))
    op.drop_column('alerts', 'sent_at')
    op.drop_column('alerts', 'recipient')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('recipient', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('alerts', 'message')
    op.drop_column('alerts', 'alert_type')
    # ### end Alembic commands ###
