"""Add server timestamp defaults

Revision ID: d150ff2dbc5b
Revises: 43b5cf6c0d38
Create Date: 2026-07-25 01:49:57.671747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd150ff2dbc5b'
down_revision: Union[str, Sequence[str], None] = '43b5cf6c0d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
